### ISSUE TITLE
Routing corrections on login and signup files, refactoring 

### ISSUE THREAD

**Issue by RaghavDoda** [Pratham1504/TeamSync#1]
After Signing up redirect to the login page and after logging in redirect to the landing page.
Also refactor the code of these two pages.

**Comment by dhaneshragu** [comment]
I would like to work on this

**Comment by ptayal76** [comment]
Assigned to @dhaneshragu

**Comment by sidling1** [comment]
Can i work on this ?

**Comment by vivekreddy049** [comment]
can you assign it to me @ptayal76
